services:
  - type: web
    name: cms-blog
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'node server.js'
    envVars:
      - key: DB_URI_INTERNAL
        fromDatabase:
          name: your-database-name
          property: connectionString
      - key: SECRET
        value: your_secret_key
