services:
  - type: web
    name: Content_Management_System
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'node server.js'
    envVars:
      - key: DB_NAME
        value: your_database_name
      - key: DB_USER
        value: your_database_user
      - key: DB_PASSWORD
        value: your_database_password
      - key: DB_HOST
        value: your_database_host
      - key: DB_PORT
        value: '5432'
      - key: SECRET
        value: your_secret_key
